-- Generated by `drizzle-kit generate`, header added — RUN-5, UX v1.2 §3.13,
-- §4.13g (TD-21). A day snapshots what its plan decided: `anchor_time` (the
-- wake) and `work_start_time` already existed; the other three anchors and
-- the fixtures the plan leaves out are added here, written at the week build
-- from the day plan or the work-day type and honoured by every re-lay
-- (`profileForDay`; the materialiser's fixture pass). Null / empty = the
-- profile's value and nothing excluded, exactly as `work_start_time` means it.
--
-- ADDITIVE ONLY. The drops planned for `0008` (RUN-15) are now `0009`.
-- Applied by Taylor after `0007`, never by an agent on a hosted tier.
ALTER TABLE "days" ADD COLUMN "work_end_time" time;--> statement-breakpoint
ALTER TABLE "days" ADD COLUMN "lights_out_time" time;--> statement-breakpoint
ALTER TABLE "days" ADD COLUMN "devices_off_time" time;--> statement-breakpoint
ALTER TABLE "days" ADD COLUMN "excluded_fixture_ids" uuid[] DEFAULT '{}' NOT NULL;