-- Generated by `drizzle-kit generate`, header added — DAY-4, UX v1.3 §11
-- (TD-25, TD-26, TD-27, TD-28, TD-30). The generated statements are unchanged.
--
--   · `block_kind` gains `transition` (the after-work hand-off), placed BEFORE
--     'activity' so the enum reads in the day's order. Its own statement, as
--     `0004` and `0007` did; nothing in this migration uses the new value.
--   · `link_kind` (spotify · other) and `links` — owner-private (the standard
--     four policies), archived never deleted, the kind derived by the service.
--   · `fixtures` gains a place and travel: `location` (≤ 80, null), and the
--     three columns a workout has — `travel_there_min`, `travel_back_min`
--     (0–180, default 0), `plan_travel` (default true). Existing rows read
--     null, 0, 0, true.
--   · `day_plans` gains `after_work_template_id` and `activity_template_id`,
--     both `ON DELETE SET NULL` and indexed; null on every existing plan.
--   · `users.same_morning_routine` — nullable, no default: not yet asked.
--
-- ADDITIVE ONLY. Nothing is dropped, renamed, or retyped; RUN-15's drops are
-- `0010_retirements` (DAY-13). Applied by Taylor after `0004`–`0008`, in order,
-- never by an agent on any tier.
CREATE TYPE "public"."link_kind" AS ENUM('spotify', 'other');--> statement-breakpoint
ALTER TYPE "public"."block_kind" ADD VALUE 'transition' BEFORE 'activity';--> statement-breakpoint
CREATE TABLE "links" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone,
	"kind" "link_kind" DEFAULT 'other' NOT NULL,
	"sort_order" smallint DEFAULT 0 NOT NULL,
	"title" text NOT NULL,
	"url" text NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "links_title_check" CHECK (length("links"."title") BETWEEN 1 AND 80),
	CONSTRAINT "links_url_check" CHECK (length("links"."url") BETWEEN 1 AND 2048)
);
--> statement-breakpoint
ALTER TABLE "links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "same_morning_routine" boolean;--> statement-breakpoint
ALTER TABLE "fixtures" ADD COLUMN "location" text;--> statement-breakpoint
ALTER TABLE "fixtures" ADD COLUMN "plan_travel" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "fixtures" ADD COLUMN "travel_back_min" smallint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "fixtures" ADD COLUMN "travel_there_min" smallint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "day_plans" ADD COLUMN "activity_template_id" uuid;--> statement-breakpoint
ALTER TABLE "day_plans" ADD COLUMN "after_work_template_id" uuid;--> statement-breakpoint
ALTER TABLE "links" ADD CONSTRAINT "links_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "links_user_id_sort_order_idx" ON "links" USING btree ("user_id","sort_order");--> statement-breakpoint
CREATE INDEX "links_user_id_archived_at_idx" ON "links" USING btree ("user_id","archived_at");--> statement-breakpoint
CREATE INDEX "links_user_id_idx" ON "links" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "day_plans" ADD CONSTRAINT "day_plans_activity_template_id_templates_id_fk" FOREIGN KEY ("activity_template_id") REFERENCES "public"."templates"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "day_plans" ADD CONSTRAINT "day_plans_after_work_template_id_templates_id_fk" FOREIGN KEY ("after_work_template_id") REFERENCES "public"."templates"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "day_plans_after_work_template_id_idx" ON "day_plans" USING btree ("after_work_template_id");--> statement-breakpoint
CREATE INDEX "day_plans_activity_template_id_idx" ON "day_plans" USING btree ("activity_template_id");--> statement-breakpoint
ALTER TABLE "fixtures" ADD CONSTRAINT "fixtures_location_check" CHECK ("fixtures"."location" IS NULL OR length("fixtures"."location") <= 80);--> statement-breakpoint
ALTER TABLE "fixtures" ADD CONSTRAINT "fixtures_travel_check" CHECK ("fixtures"."travel_there_min" BETWEEN 0 AND 180 AND "fixtures"."travel_back_min" BETWEEN 0 AND 180);--> statement-breakpoint
CREATE POLICY "links_select" ON "links" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("links"."user_id" = current_setting('app.user_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "links_insert" ON "links" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("links"."user_id" = current_setting('app.user_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "links_update" ON "links" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("links"."user_id" = current_setting('app.user_id', true)::uuid) WITH CHECK ("links"."user_id" = current_setting('app.user_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "links_delete" ON "links" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("links"."user_id" = current_setting('app.user_id', true)::uuid);