-- Generated by `drizzle-kit generate`, header added — DAY-13, UX v1.3 TD-30.
-- The generated statements are unchanged.
--
-- RUN-15's three drops, carried into Epic 6 (RUN-15 is superseded). Nothing
-- has read or written these since RUN-8 / RUN-9:
--
--   · `users.earliest_wake_time` — the wake range's early end (v1.2 R39).
--   · `users.orient_passage` — the one morning passage; `0007` copied every
--     non-blank value into `passages`. Its length check goes with it.
--   · `users.orient_show_last_night` — the last-night switch (v1.2 R41).
--
-- Nothing else is dropped, renamed or retyped. AUTHORED AND JOURNALLED ONLY —
-- not applied to any tier; Taylor runs it after `0009` on staging.
ALTER TABLE "users" DROP CONSTRAINT "users_orient_passage_check";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "earliest_wake_time";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "orient_passage";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "orient_show_last_night";
