/**
 * Two generated views of docs/, both from frontmatter, neither written by hand:
 *
 *  1. docs/_generated/directory-map.md: every file under docs/, one line each,
 *     grouped by folder. A listing, not a map (CF-05): docs/index.md says how
 *     the layers relate; this says what each file is for.
 *  2. The "In this folder" table at the foot of every folder's README.md. The
 *     top of a README is written by a person (what the folder is, when to come
 *     here, where to start); everything below the marker line is rewritten.
 *
 * A file's line is its frontmatter `description`; a folder's line is its
 * README's `description`. Never loaded by agents (docs/index.md, "Never").
 *
 *   yarn directory-map           write both
 *   yarn directory-map --check   exit 1 if either is out of date, or a folder has no README
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

import { listMarkdown, readMarkdown, REPO_ROOT } from "./lib/docs.ts";
import { loadToolkit } from "./lib/toolkit.ts";

// An overlay leaves the host repo's docs alone (report §1, adoption tiers).
if (loadToolkit().tier !== "starter") {
  console.log(
    "directory-map — skipped: the overlay tiers do not map host docs.",
  );
  process.exit(0);
}

const DOCS = "docs";
const OUT = "docs/_generated/directory-map.md";
const LANDING = "README.md";
const MARKER =
  "<!-- Generated by `yarn directory-map` from each file's frontmatter. Everything below this line is rewritten; edit above it. -->";
const check = process.argv.includes("--check");

const abs = (rel: string) => path.join(REPO_ROOT, rel);
const files = listMarkdown(DOCS).filter(
  (f) => !f.startsWith("docs/_generated/"),
);

/** A filed bundle (a skill with its SKILL.md) keeps its own shape; no landing pages inside it. */
function insideBundle(dir: string): boolean {
  let current = dir;
  while (current !== DOCS && current !== ".") {
    if (existsSync(abs(`${current}/SKILL.md`))) return true;
    current = path.posix.dirname(current);
  }
  return false;
}

/** Every folder under docs/ that takes a landing page, docs/ itself first. */
function folders(): string[] {
  const found = new Set<string>([DOCS]);
  for (const file of files) {
    let dir = path.posix.dirname(file);
    while (dir !== DOCS) {
      found.add(dir);
      dir = path.posix.dirname(dir);
    }
  }
  return [...found]
    .filter((dir) => !dir.startsWith("docs/_generated") && !insideBundle(dir))
    .sort((a, b) => (a === DOCS ? -1 : b === DOCS ? 1 : a.localeCompare(b)));
}

const cell = (value: unknown) =>
  String(value ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\s+/g, " ")
    .trim();

const description = (file: string) =>
  existsSync(abs(file))
    ? readMarkdown(file).frontmatter?.description
    : undefined;

const landingOf = (dir: string) => `${dir}/${LANDING}`;
const isLanding = (file: string) => path.posix.basename(file) === LANDING;

const errors: string[] = [];
const landings = folders();
const landingSet = new Set(landings.map(landingOf));

// ---------------------------------------------------------------- README tables

function folderTable(dir: string): string {
  const entries = readdirSync(abs(dir), { withFileTypes: true });
  const rows: string[] = [];
  const own = entries
    .filter(
      (entry) =>
        entry.isFile() && entry.name !== LANDING && !entry.name.startsWith("."),
    )
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of own) {
    const rel = `${dir}/${entry.name}`;
    const what = entry.name.endsWith(".md")
      ? cell(description(rel))
      : `A \`${path.extname(entry.name).slice(1) || "text"}\` file; see the notes above.`;
    rows.push(`| [\`${entry.name}\`](${entry.name}) | ${what} |`);
  }
  const subs = entries
    .filter(
      (entry) =>
        entry.isDirectory() &&
        landingSet.has(landingOf(`${dir}/${entry.name}`)),
    )
    .sort((a, b) => a.name.localeCompare(b.name));
  for (const entry of subs) {
    const rel = `${dir}/${entry.name}`;
    rows.push(
      `| [\`${entry.name}/\`](${entry.name}/${LANDING}) | ${cell(description(landingOf(rel)))} |`,
    );
  }
  return [
    "## In this folder",
    "",
    "| File | What it is for |",
    "| --- | --- |",
    ...rows,
  ].join("\n");
}

function renderLanding(dir: string): {
  current: string | null;
  next: string | null;
} {
  const file = landingOf(dir);
  if (!existsSync(abs(file))) {
    errors.push(
      `${dir}/ has no ${LANDING}. Create it: the frontmatter block, a title, what the folder is, ` +
        `when to come here and where to start, then run \`yarn directory-map\` to append the file table.`,
    );
    return { current: null, next: null };
  }
  const current = readFileSync(abs(file), "utf8");
  const at = current.indexOf(MARKER);
  const top = (at === -1 ? current : current.slice(0, at)).trimEnd();
  return { current, next: `${top}\n\n${MARKER}\n\n${folderTable(dir)}\n` };
}

// ---------------------------------------------------------------- the full listing

const fromHere = (target: string) =>
  path.posix.relative("docs/_generated", target);

function renderMap(): string {
  const byFolder = new Map<string, string[]>();
  for (const file of files) {
    const dir = path.posix.dirname(file);
    byFolder.set(dir, [...(byFolder.get(dir) ?? []), file]);
  }
  const dirs = [...byFolder.keys()].sort((a, b) =>
    a === DOCS ? -1 : b === DOCS ? 1 : a.localeCompare(b),
  );
  const sections: string[] = [];
  for (const dir of dirs) {
    const folderFiles = byFolder
      .get(dir)!
      .sort((a, b) =>
        isLanding(a) === isLanding(b)
          ? a.localeCompare(b)
          : isLanding(a)
            ? -1
            : 1,
      );
    sections.push("", `## \`${dir}/\``, "");
    const purpose = description(landingOf(dir));
    if (purpose) sections.push(cell(purpose), "");
    sections.push("| File | What it is for | Status |", "| --- | --- | --- |");
    for (const file of folderFiles) {
      const fm = readMarkdown(file).frontmatter ?? {};
      sections.push(
        `| [\`${path.posix.basename(file)}\`](${fromHere(file)}) | ${cell(fm.description)} | ${cell(fm.status)} |`,
      );
    }
  }
  return [
    "---",
    "title: Directory map — every file, one line each",
    "description: Read when you want to know what a file under docs/ is for without opening it; generated from each file's frontmatter.",
    "layer: decisions",
    "status: adopted",
    "---",
    "",
    "# Directory map",
    "",
    `Every markdown file under \`docs/\` (${files.length}), grouped by folder. Generated by \`yarn directory-map\` from each file's \`description\`, which is written as a trigger: it says when to read the file. Do not edit by hand; CI fails when this is out of date. Each folder's own \`README.md\` carries the same table for that folder. How the layers relate, and what loads when, is in [\`docs/index.md\`](../index.md).`,
    ...sections,
    "",
  ].join("\n");
}

// ---------------------------------------------------------------- run

const stale: string[] = [];
const writes: [string, string][] = [];
for (const dir of landings) {
  const { current, next } = renderLanding(dir);
  if (next !== null && next !== current) {
    stale.push(landingOf(dir));
    writes.push([landingOf(dir), next]);
  }
}
const map = renderMap();
const mapCurrent = existsSync(abs(OUT)) ? readFileSync(abs(OUT), "utf8") : null;
if (map !== mapCurrent) {
  stale.push(OUT);
  writes.push([OUT, map]);
}

if (errors.length > 0) {
  console.error(
    `directory-map — ${errors.length} problem(s):\n  ${errors.join("\n  ")}`,
  );
  process.exit(1);
}
if (check) {
  if (stale.length > 0) {
    console.error(
      `directory-map — out of date; run \`yarn directory-map\` and commit:\n  ${stale.join("\n  ")}`,
    );
    process.exit(1);
  }
  console.log(
    `directory-map — up to date (${files.length} files, ${landings.length} landing pages).`,
  );
} else {
  for (const [file, text] of writes) {
    mkdirSync(path.dirname(abs(file)), { recursive: true });
    writeFileSync(abs(file), text);
  }
  const pages = writes.length - (map !== mapCurrent ? 1 : 0);
  console.log(
    `directory-map — ${files.length} files → ${OUT}; ${pages} of ${landings.length} landing pages rewritten.`,
  );
}
