/**
 * Generates .claude/agents/<name>.md from role prompts under docs/roles/
 * whose frontmatter opts in with `subagent: true` (record 0008).
 *
 *   yarn gen:agents           write the agents, delete stale ones
 *   yarn gen:agents --check   exit 1 if .claude/agents/ differs from the roles
 *
 * Role frontmatter read here:
 *   description                 the subagent's trigger description
 *   subagent: true              opt in
 *   subagent_tools              allowlist (bare tool names); absent = inherit all
 *   subagent_disallowed_tools   denylist (may use permission specifiers)
 *   subagent_model              optional model alias
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

import { listMarkdown, readMarkdown, REPO_ROOT } from "./lib/docs.ts";

const ROLES_DIR = "docs/roles";
const AGENTS_DIR = ".claude/agents";
const check = process.argv.includes("--check");

type Agent = { name: string; source: string; content: string };

/**
 * Ruling (c), E-31: the index's precedence is the only authority ladder. A
 * ladder inside a role body describes reading order at most.
 */
const BANNER =
  "> **Precedence:** `docs/index.md` §Precedence governs. Any authority ladder in the role below is reading order only; where they differ, the index wins.";

function yamlString(value: string) {
  return JSON.stringify(value);
}

function toolList(
  value: unknown,
  source: string,
  key: string,
): string[] | null {
  if (value === undefined || value === null) return null;
  if (!Array.isArray(value) || !value.every((v) => typeof v === "string")) {
    throw new Error(`${source}: ${key} must be a list of tool names`);
  }
  return value as string[];
}

function build(source: string): Agent | null {
  const md = readMarkdown(source);
  const fm = md.frontmatter;
  if (!fm || fm.subagent !== true) return null;

  const name = path.posix.basename(source, ".md").split("-")[0]!;
  const description = fm.description;
  if (typeof description !== "string" || description.length === 0) {
    throw new Error(`${source}: a subagent needs a description`);
  }
  const tools = toolList(fm.subagent_tools, source, "subagent_tools");
  const disallowed = toolList(
    fm.subagent_disallowed_tools,
    source,
    "subagent_disallowed_tools",
  );

  const head = [`name: ${name}`, `description: ${yamlString(description)}`];
  if (tools) head.push(`tools: ${tools.join(", ")}`);
  if (disallowed) head.push(`disallowedTools: ${disallowed.join(", ")}`);
  if (typeof fm.subagent_model === "string")
    head.push(`model: ${fm.subagent_model}`);

  const notice =
    `<!-- GENERATED by tooling/gen-agents.ts from ${source}. ` +
    "Do not edit: change the role, then run `yarn gen:agents`. -->";
  const content = `---\n${head.join("\n")}\n---\n\n${notice}\n\n${BANNER}\n\n${md.body.trimStart()}`;
  return { name, source, content };
}

const agents = listMarkdown(ROLES_DIR)
  .map(build)
  .filter((agent): agent is Agent => agent !== null);

const names = new Set<string>();
for (const agent of agents) {
  if (names.has(agent.name))
    throw new Error(`two roles generate the agent "${agent.name}"`);
  names.add(agent.name);
}

const dir = path.join(REPO_ROOT, AGENTS_DIR);
const existing = existsSync(dir)
  ? readdirSync(dir).filter((f) => f.endsWith(".md"))
  : [];
const expected = new Map(agents.map((a) => [`${a.name}.md`, a]));
const problems: string[] = [];

for (const file of existing) {
  if (!expected.has(file)) {
    if (check)
      problems.push(`${AGENTS_DIR}/${file} has no role with subagent: true`);
    else unlinkSync(path.join(dir, file));
  }
}
for (const [file, agent] of expected) {
  const target = path.join(dir, file);
  const current = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (current === agent.content) continue;
  if (check) {
    problems.push(
      `${AGENTS_DIR}/${file} is ${current === null ? "missing" : "out of date"} (from ${agent.source})`,
    );
  } else {
    mkdirSync(dir, { recursive: true });
    writeFileSync(target, agent.content);
  }
}

if (problems.length > 0) {
  console.error(problems.join("\n"));
  console.error("\ngen:agents — run `yarn gen:agents` and commit the result.");
  process.exit(1);
}
const summary = agents.map((a) => `${a.name} (${a.source})`).join("\n  ");
console.log(
  `gen:agents — ${check ? "up to date" : "wrote"} ${agents.length} agent(s):\n  ${summary}`,
);
